### ISSUE TITLE
Fenced ring buffer proposal

### ISSUE THREAD

**Issue by ratchetfreak** [toomuchvoltage/GAL#2]
When uploading data to the GPU it's recommended to use double buffering or a ring buffer so the current frame doesn't have to wait until the previous frame is done to start uploading the data.

So I suggest adding a helper class for that. I foresee the usage as something like:

```C++
RingBuffer* ring = new DXD12RingBuffer(vramHeap, [range]);
Resource* uploadBuffer = ...;

void Render(){
    copyQueue->Wait(ring->fence);
    uploadBuffer->Map();
    memcpy(uploadBuffer->mappedMemory, renderData, size);
    uploadBuffer->Unmap();


    Resource *buffer = ring->push(size);

    copyCommandList->reset([...]);
    //Barrier for buffer from NON_PS_SRV to COPY_DEST
    copyCommandList->copy(uploadBuffer, buffer); // copy from uploadbuffer to vram range described in buffer
    //Barrier for buffer from COPY_DEST to NON_PS_SRV 
    copyCommandList->close();

    renderCommandList->reset([...]);
    renderCommandList->PlaceDescriptorIntoRootDescriptorTable([...]);//using the buffer's offset
    renderCommandList->Draw*([...]);
    renderCommandList->close();

    copyQueue->ExecuteList(copyCommandList);
    copyQueue->SetFence(copyFence);
    renderQueue->waitFor(copyFence); //make the queue wait until the copy is complete on the other queue
    renderQueue->ExecuteList(renderCommandList);
    copyQueue->setFence(ring->fence); //set fence on last use of the buffer
    delete buffer;
}
```

RingBuffer::Push(uint) will check its fence to ensure no overlap occurs.

**Comment by toomuchvoltage** [comment]
Ahh, yes! Thanks again for dropping by ratchetfreak! I believe we did discuss this last time... this is for async-buffer-upload-type use cases at render-time I believe. That's next up on the list! Stay tuned... 

I may also actually reach out to you regarding making a worthwhile sample for this use case.

**Comment by toomuchvoltage** [comment]
Hi ratchetfreak! so I've provided the sample we discussed earlier.

Basically, as mentioned earlier on IRC, for the time being it's basically uploading (streaming) textures using temporary placed resources that I create and destroy on a per-frame basis. MSDN guarantees to be a light operation. These placed resources also point into a shared upload heap that is created once beforehand and lives for the life of the application.

This should be much more optimal than creating and destroying textures using the normal route (with committed resources and 1-to-1-mapped heaps).

However, at this point I'm uncertain if this is truly the optimal solution. Once Microsoft comes back with a ring-buffer sample I may be able to improve this if there are dissimilarities.

I'm going to close the ticket for now, but if Microsoft comes back with a different solution, we can create a new one and take it from there.
Thanks again for collaborating!

Yours truly,
Baktash.

**Comment by toomuchvoltage** [comment]
I know this I closed this but just wanted to say that a mistake was corrected regarding waits (the wait was CPU side rather than GPU.) Also after reading comments from Bob Brown (Microsoft) it appears there's an example for ring buffers though for committed ConstantBuffers rather than textures... I was more or less thinking that's what they're mostly used for. Bob's suggestion really improved our texture streaming example though!

Cheers,
Baktash.

**Comment by ratchetfreak** [comment]
Browsing around a bit I found another repo with a D3D12 example: https://github.com/GPUOpen-LibrariesAndSDKs/HelloD3D12 from the guys at AMD's initiative http://gpuopen.com/

It's not using a ring buffer (instead several committed resourced being used in sequence for CBVs). But something to keep an eye on either way.
